version = 1

[[annotations]]
path = [
    "REUSE.toml",
    "CMakePresets.json",
    ".gitignore",
    ".gitmodules",
    "README.md",
]

precedence = "aggregate"
SPDX-FileCopyrightText = "shadNet Project"
SPDX-License-Identifier = "GPL-2.0-or-later"
