// SPDX-FileCopyrightText: Copyright 2026 shadNet Project
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#include <cstdint>

// ── Handler type indices (array index and bitmask position) ──────────────────

namespace HandlerType {
constexpr uint8_t Context = 0;
constexpr uint8_t Request = 1;
constexpr uint8_t RoomEvent = 2;
constexpr uint8_t LobbyEvent = 3;
constexpr uint8_t RoomMessage = 4;
constexpr uint8_t LobbyMessage = 5;
constexpr uint8_t Count = 6;
} // namespace HandlerType

namespace Matching2 {
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_1_ID = 0x004C;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_2_ID = 0x004D;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_3_ID = 0x004E;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_4_ID = 0x004F;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_5_ID = 0x0050;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_6_ID = 0x0051;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_7_ID = 0x0052;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_INT_ATTR_EXTERNAL_8_ID = 0x0053;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_SEARCHABLE_BIN_ATTR_EXTERNAL_1_ID = 0x0054;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_BIN_ATTR_EXTERNAL_1_ID = 0x0055;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_BIN_ATTR_EXTERNAL_2_ID = 0x0056;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_BIN_ATTR_INTERNAL_1_ID = 0x0057;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOM_BIN_ATTR_INTERNAL_2_ID = 0x0058;
constexpr uint16_t ORBIS_NP_MATCHING2_ROOMMEMBER_BIN_ATTR_INTERNAL_1_ID = 0x0059;

constexpr uint32_t ORBIS_NP_MATCHING2_ROOM_FLAG_ATTR_OWNER_AUTO_GRANT = 0x80000000;
constexpr uint32_t ORBIS_NP_MATCHING2_ROOM_FLAG_ATTR_CLOSED = 0x40000000;
constexpr uint32_t ORBIS_NP_MATCHING2_ROOM_FLAG_ATTR_FULL = 0x20000000;
constexpr uint32_t ORBIS_NP_MATCHING2_ROOM_FLAG_ATTR_HIDDEN = 0x10000000;
constexpr uint32_t ORBIS_NP_MATCHING2_ROOM_FLAG_ATTR_NAT_TYPE_RESTRICTION = 0x04000000;
constexpr uint32_t ORBIS_NP_MATCHING2_ROOM_FLAG_ATTR_PROHIBITIVE_MODE = 0x02000000;

constexpr uint32_t ORBIS_NP_MATCHING2_ROOMMEMBER_FLAG_ATTR_OWNER = 0x80000000;

constexpr uint8_t ORBIS_NP_MATCHING2_ROLE_MEMBER = 1;
constexpr uint8_t ORBIS_NP_MATCHING2_ROLE_OWNER = 2;

constexpr uint32_t ORBIS_NP_MATCHING2_SESSION_PASSWORD_SIZE = 8;
constexpr uint32_t ORBIS_NP_MATCHING2_GROUP_LABEL_SIZE = 8;
} // namespace Matching2
